function fowl(){var X='',eb='" for "gwt:onLoadErrorFn"',cb='" for "gwt:onPropertyErrorFn"',ob='"><\/script>',fb='#',vb='.cache.js',hb='/',ub=':',Y='::',M='<html><head><\/head><body><\/body><\/html>',nb='<script id="',_='=',gb='?',bb='Bad handler "',tb='C40F8A45EF6BE6C99A7AFE887F665D61',Q='DOMContentLoaded',H='DUMMY',pb='SCRIPT',mb='__gwt_marker_fowl',qb='base',kb='baseUrl',C='begin',I='body',B='bootstrap',jb='clear.cache.gif',$='content',sb='devmode.js',xb='end',F='fowl',lb='fowl.nocache.js',W='fowl::',E='gwt.codesvr=',db='gwt:onLoadErrorFn',ab='gwt:onPropertyErrorFn',Z='gwt:property',T='head',J='iframe',ib='img',O='javascript',K='javascript:""',wb='loadExternalRefs',U='meta',S='moduleRequested',R='moduleStartup',V='name',L='position:absolute; width:0; height:0; border:none; left: -1000px; top: -1000px; !important',N='script',rb='selectingPermutation',G='startup',D='undefined',P='var $wnd = window.parent;';var n=window;var o=document;r(B,C);function p(){if(typeof o.readyState==D){return typeof o.body!=D&&o.body!=null}return /loaded|complete/.test(o.readyState)}
function q(){var a=n.location.search;return a.indexOf(E)!=-1}
function r(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:F,sessionId:n.__gwtStatsSessionId,subSystem:G,evtGroup:a,millis:(new Date).getTime(),type:b})}}
fowl.__sendStats=r;fowl.__moduleName=F;fowl.__errFn=null;fowl.__moduleBase=H;fowl.__softPermutationId=0;fowl.__computePropValue=null;var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;function u(e){var f;function g(){i();return f}
function h(){i();return f.getElementsByTagName(I)[0]}
function i(){if(f){return}var a=o.createElement(J);a.src=K;a.id=F;a.style.cssText=L;a.tabIndex=-1;o.body.appendChild(a);f=a.contentDocument;if(!f){f=a.contentWindow.document}f.open();f.write(M);f.close();var b=f.getElementsByTagName(I)[0];var c=f.createElement(N);c.language=O;var d=P;c.text=d;b.appendChild(c)}
function j(a){var b=false;if(p()){b=true;a()}var c;function d(){if(!b){b=true;a();if(o.removeEventListener){o.removeEventListener(Q,d,false)}if(c){clearInterval(c)}}}
if(o.addEventListener){o.addEventListener(Q,function(){d()},false)}var c=setInterval(function(){if(p()){d()}},50)}
function k(a){var b=h();var c=g().createElement(N);c.language=O;c.text=a;b.appendChild(c);b.removeChild(c)}
fowl.onScriptDownloaded=function(a){j(function(){k(a)})};r(R,S);var l=o.createElement(N);l.src=e;o.getElementsByTagName(T)[0].appendChild(l)}
function v(){var c={};var d;var e;var f=o.getElementsByTagName(U);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(V),k;if(j){j=j.replace(W,X);if(j.indexOf(Y)>=0){continue}if(j==Z){k=i.getAttribute($);if(k){var l,m=k.indexOf(_);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=X}c[j]=l}}else if(j==ab){k=i.getAttribute($);if(k){try{d=eval(k)}catch(a){alert(bb+k+cb)}}}else if(j==db){k=i.getAttribute($);if(k){try{e=eval(k)}catch(a){alert(bb+k+eb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;fowl.__errFn=e}
function w(){function e(a){var b=a.lastIndexOf(fb);if(b==-1){b=a.length}var c=a.indexOf(gb);if(c==-1){c=a.length}var d=a.lastIndexOf(hb,Math.min(c,b));return d>=0?a.substring(0,d+1):X}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(ib);b.src=a+jb;a=e(b.src)}return a}
function g(){var a=t(kb);if(a!=null){return a}return X}
function h(){var a=o.getElementsByTagName(N);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(lb)!=-1){return e(a[b].src)}}return X}
function i(){var a;if(typeof p==D||!p()){var b=mb;var c;o.write(nb+b+ob);c=o.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=pb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return X}
function j(){var a=o.getElementsByTagName(qb);if(a.length>0){return a[a.length-1].href}return X}
var k=g();if(k==X){k=h()}if(k==X){k=i()}if(k==X){k=j()}if(k==X){k=e(o.location.href)}k=f(k);base=k;return k}
function x(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return fowl.__moduleBase+a}
function y(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
s=function(a,b){return b in h[a]};fowl.__computePropValue=j;r(B,rb);if(q()){return x(sb)}var k;try{k=tb;var l=k.indexOf(ub);if(l!=-1){g=k.substring(l+1);k=k.substring(0,l)}}catch(a){}fowl.__softPermutationId=g;return x(k+vb)}
function z(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}r(wb,C);r(wb,xb)}
v();fowl.__moduleBase=w();var A=y();z();r(B,xb);u(A)}
fowl();